### ISSUE TITLE
Jekyll and Asciidoctor Diagram 2.1.2: attribute 'syntrax-style' ignored (works with Asciidoctor Diagram 2.1.1)

### ISSUE THREAD

**Issue by ianss** [asciidoctor/asciidoctor-diagram#350]
The attribute `:syntrax-style:` is ignored by Asciidoctor Diagram 2.1.2 when building a Jekyll site with the following Gemfile spec:

```
source 'https://rubygems.org'

gem "jekyll", "4.1.1"
gem "asciidoctor", "2.0.12"
gem "pygments.rb"
gem "aws-sdk-s3"

group :jekyll_plugins do
  gem "asciidoctor-diagram", "2.1.2"
  gem "jekyll-asciidoc"
end
```

Last known working Gemfile spec:

```
source 'https://rubygems.org'

gem "jekyll", "4.1.1"
gem "asciidoctor", "2.0.12"
gem "pygments.rb"
gem "aws-sdk-s3"

group :jekyll_plugins do
  gem "asciidoctor-diagram", "2.1.1"
  gem "jekyll-asciidoc"
end
```

I set the `:syntrax-style:` attribute in Jekyll's `_config.yml` file:

```yaml
asciidoctor:
  safe: unsafe
  attributes:
    plantuml-config: "{site-source}/assets/plantuml/config.plantuml"
    syntrax-style: "{site-source}/assets/syntrax/syntrax.ini"
    diagram-svg-type: inline
```

I have tried both relative and absolute values for `:syntrax-style:`. Neither work with Asciidoctor Diagram 2.1.2.

My thanks to all who contribute to Asciidoctor Diagram. It's a great project and I use it regularly with Jekyll and Asciidoctor PDF.
